konveyor/move2kube-ui

- .dockerignore
- .gitignore
- Dockerfile
- LICENSE
- README.md
- docker-compose.yml
- dr-surge.js
- package-lock.json
- package.json
- server.js
- src/app/index.tsx
- src/index.html
- src/index.tsx
- tsconfig.json
- webpack.common.js
- webpack.dev.js
- webpack.prod.js
> Initial simple empty website with Patternfly

- .travis.yml
- Makefile
- README.md
> Update Makefile to support features

- .gitignore
- Dockerfile
- Makefile
- docker-compose.yml
- server.js
> Fix docker compose

- .gitignore
- docker-compose.yml
> Change default wksps folder in docker compose

- code-of-conduct.md
- contributing.md
> Add code of conduct and contributing docs

- README.md
> Fix github url in README

- README.md
> Fix http urls in badges

- .dockerignore
- .gitignore
- Dockerfile
- docker-compose.yml
I optimized the base image which was smaller before, up to 1GB, now it is only 300 MB, I tidy up the writing structure and I update the docker-compose file to build automatically when it's up.
> optimasi dockerfile & docker-compose

- README.md
> Update ReadMe with docker instructions

- README.md
> Add docker-compose based access instructions

- .github/workflows/build.yml
- .github/workflows/prbuild.yml
- .github/workflows/release.yml
- Makefile
> Support Github Actions

- .github/workflows/build.yml
- .github/workflows/tag.yml
> Add Tag github action

- .github/workflows/prbuild.yml
- .github/workflows/release.yml
- README.md
> Add Github actions badge

- .github/workflows/release.yml
> Add release draft creation notification

- .github/workflows/assignproject.yml
> Auto assign issue to project

- .github/workflows/assignproject.yml
- .github/workflows/release.yml
- .github/workflows/tag.yml
- .grenrc.js
> fix: release workflow to match the cli release workflow

- .github/workflows/assignproject.yml
- .github/workflows/build.yml
- .github/workflows/prbuild.yml
> fix: reformat workflow files

- src/app/QA/Confirm.tsx
- src/app/QA/Input.tsx
- src/app/QA/MultiSelect.tsx
- src/app/QA/Multiline.tsx
- src/app/QA/Password.tsx
- src/app/QA/Select.tsx
Show the hint with the questions and also show the default value for input question type. https://github.com/konveyor/move2kube-ui/issues/29
> fix: Show the hint and the default value

- .github/workflows/build.yml
- .github/workflows/prbuild.yml
- contributing.md
> chore: Change default branch to main

- src/app/QA/Password.tsx
> fix: QA bug in Password type

- src/app/QA/Confirm.tsx
Fix https://github.com/konveyor/move2kube-ui/issues/29 Signed-off-by: Akash Nayak <akash19nayak@gmail.com>
> fix: QA bug in Confirm type

- src/app/Application/ApplicationAssets.tsx
Fix https://github.com/konveyor/move2kube-ui/issues/45 
> fix: Update the Move2Kube command line tool download url

- .dockerignore
- .gitignore
- docker-compose.yml
> fix: Change default dir to workspace

- .github/workflows/build.yml
- .github/workflows/labelpr.yml
- .github/workflows/release.yml
- Dockerfile.aio
- Makefile
- README.md
> feat: Add support for all-in-one container

- .github/workflows/build.yml
- .github/workflows/prbuild.yml
- .github/workflows/release.yml
- .github/workflows/tag.yml
- .grenrc.js
- Makefile
> ci: clean up workflows to work together across multiple repos

- Dockerfile
- Dockerfile.aio
> fix: Optimize container image size and use fedora as base image

- Dockerfile.aio
- src/app/Support/Support.tsx
> fix: Change support link to point to website

- package.json
- src/app/Application/Application.tsx
- src/app/Application/ApplicationPlan.tsx
- src/app/Applications/Applications.tsx
- src/app/QA/Wizard.tsx
Added support for debug flag in the url to print the debug logs for move2kube `plan` and `translate` https://github.com/konveyor/move2kube-api/issues/25
> feat: Add support for move2kube debug mode

- .github/workflows/build.yml
- Dockerfile.aio
> fix: Change notification message on image build

- src/app/Application/ApplicationArtifacts.tsx
- src/app/QA/Wizard.tsx
Fixes: https://github.com/konveyor/move2kube-ui/issues/61
> fix: Disable Next button after pressing it and between next question is flashed

- src/app/QA/Confirm.tsx
- src/app/QA/Input.tsx
- src/app/QA/MultiSelect.tsx
- src/app/QA/Multiline.tsx
- src/app/QA/Password.tsx
- src/app/QA/Select.tsx
- src/app/QA/Wizard.tsx
> feat: Send problem obj as solution

- .grenrc.js
- README.md
- src/app/Application/ApplicationAssets.tsx
- src/app/Support/Support.tsx
> chore: update move2kube website url

- src/app/Application/Application.tsx
- src/app/Application/ApplicationAssets.tsx
- src/app/Application/ApplicationContext.tsx
- src/app/Application/ApplicationPlan.tsx
Allow users to edit the plan in addition to being
able to select the containerization option.
Also fixes some issues with how context is manipulated.
> feat: make the plan edittable

- server.js
- src/app/Application/Application.tsx
- src/app/Application/ApplicationArtifacts.tsx
- src/app/Application/ApplicationAssets.tsx
- src/app/Application/ApplicationContext.tsx
- src/app/Application/ApplicationPlan.tsx
- src/app/Application/GuidedFlow.tsx
- src/app/Application/NewApplication.tsx
- src/app/Applications/Applications.tsx
- src/app/Networking/api.ts
- src/app/routes.tsx
> feat: add a flow to guide users through the full translation process

- Makefile
- README.md
- docker-compose.dev.yml
- docker-compose.yml
- package.json
- server.js
- src/app/Networking/api.ts
- src/app/Support/Support.tsx
> feat: provide more info about image hashes and ui dockerfile

- src/app/Application/Application.tsx
- src/app/Application/ApplicationContext.tsx
- src/app/Application/ApplicationPlan.tsx
- src/app/Application/GuidedFlow.tsx
> feat: view and edit the plan in the guided flow

- src/app/QA/Confirm.tsx
- src/app/QA/Input.tsx
- src/app/QA/MultiSelect.tsx
- src/app/QA/Multiline.tsx
- src/app/QA/Password.tsx
- src/app/QA/QAWizard.tsx
- src/app/QA/Select.tsx
- src/app/QA/Types.ts
> chore: change the logic to handle the new problem struct

- src/app/Application/ApplicationAssets.tsx
> fix: progress events for upload are fired on xhr.upload, progress events for download are fired on xhr

- src/app/Application/Application.tsx
- src/app/Application/ApplicationArtifacts.tsx
- src/app/Application/ApplicationAssets.tsx
- src/app/Application/ApplicationPlan.tsx
- src/app/Application/GuidedFlow.tsx
- src/app/Application/Types.ts
- src/app/Applications/Applications.tsx
> feat: support move2kube v0.3

- src/app/Application/Application.tsx
- src/app/Application/ApplicationPlan.tsx
- src/app/Application/GuidedFlow.tsx
- src/app/Application/Types.ts
- src/app/Networking/api.ts
> fix: plan not displaying properly in the plan tab outside of guided flow

- .dockerignore
- Dockerfile
- Dockerfile.aio
- Dockerfile.dev
> refactor: Change base image to ubi8

- src/app/Application/Application.tsx
- src/app/Application/ApplicationArtifacts.tsx
- src/app/Application/ApplicationAssets.tsx
- src/app/Application/ApplicationPlan.tsx
- src/app/Application/GuidedFlow.tsx
- src/app/Application/Types.ts
- src/app/Networking/api.ts
- src/app/app.css
> feat: allow uploading the customization directory

- server.js
> feat: allow encrypted SAML assertions

- server.js
> feat: disable SAML validation

- README.md
> chore: update readme with new commands

- .github/workflows/build.yml
- .github/workflows/prbuild.yml
- .github/workflows/release.yml
> fix: set default shell to bash for consistency

- src/app/projects/ProjectOutputs.tsx
fix: the extension should not be normalized along with the filename
> feat: open the qa wizard after clicking start transformation

- Makefile
> fix: Fix tab space in dockerfile for container runtime check

- src/app/common/types.ts
- src/app/common/utils.ts
- src/app/networking/api.ts
- src/app/networking/login.ts
- src/app/projects/ProjectInputs.tsx
- src/app/projects/ProjectOutputs.tsx
- src/app/projects/Projects.tsx
- src/app/workspaces/Workspaces.tsx
> feat: show error when delete fails

- src/app/projects/Projects.tsx
> chore: rearrange the UI so list of projects in a workspace is at the top of the page

- src/app/projects/ProjectOutputs.tsx
- src/app/qa/QAWizard.tsx
> fix: QA state was being shared between different transformation runs

- src/app/common/types.ts
- src/app/qa/Input.tsx
- src/app/qa/QAContext.tsx
- src/app/qa/QAWizard.tsx
> feat: allow pressing Enter inside text input in QA Wizard to move to the next step

- .github/workflows/release.yml
- Makefile
- README.md
- helm-charts/move2kube/Chart.yaml
- helm-charts/move2kube/LICENSE
- helm-charts/move2kube/README.md
- helm-charts/move2kube/templates/NOTES.txt
- helm-charts/move2kube/templates/auth-server-deployment.yaml
- helm-charts/move2kube/templates/auth-server-secret.yaml
- helm-charts/move2kube/templates/auth-server-service.yaml
- helm-charts/move2kube/templates/database-deployment.yaml
- helm-charts/move2kube/templates/database-service.yaml
- helm-charts/move2kube/templates/move2kube-api-headless-service.yaml
- helm-charts/move2kube/templates/move2kube-api-ingress.yaml
- helm-charts/move2kube/templates/move2kube-api-route.yaml
- helm-charts/move2kube/templates/move2kube-api-secret.yaml
- helm-charts/move2kube/templates/move2kube-api-service.yaml
- helm-charts/move2kube/templates/move2kube-api-stateful-set.yaml
- helm-charts/move2kube/templates/persistent-volume-claim.yaml
- helm-charts/move2kube/templates/security-context-constraints.yaml
- helm-charts/move2kube/templates/service-account.yaml
- helm-charts/move2kube/values.schema.json
- helm-charts/move2kube/values.yaml
> chore: move over the helm chart for the ui from the operator repo

- .github/workflows/release.yml
> chore: remove reference to personal repos/forks

- .gitignore
- package.json
- src/app/assets/app.css
- src/app/networking/api.ts
- src/app/projects/ProjectOutputGraph.tsx
- src/app/projects/ProjectOutputs.tsx
- src/app/qa/Confirm.tsx
- src/app/qa/Hints.tsx
- src/app/qa/Input.tsx
- src/app/qa/MultiSelect.tsx
- src/app/qa/Multiline.tsx
- src/app/qa/Password.tsx
- src/app/qa/Select.tsx
- yarn.lock
chore: ignore the vscode settings directory
> feat: add button to fetch and show the graph after doing a tranformation

- README.md
- webpack.common.js
> fix: add back the favicon and fix type

- helm-charts/move2kube/templates/auth-server-service.yaml
> chore: fix a minor typo in the helm chart

- src/app/qa/QAWizard.tsx
> fix: reenable the next button when there is a validation error during QA

- src/features/common/constants.ts
- src/features/outputs/outputsApi.ts
- src/features/outputs/qa/QAWizard.tsx
> chore: some minor fixes, refetch project outputs when qa is cancelled

- src/features/plan/planApi.ts
Signed-off-by: Mehant Kammakomati <mehant.kammakomati2@ibm.com>
> fix: poll for status accepted

- src/app/store.ts
- src/features/plan/Plan.tsx
- src/features/plan/planApi.ts
- src/features/plan/planSlice.ts
- src/features/projects/Project.tsx
- src/index.css
Also disable the `start transformation` button while planning.
> feat: show the progress while planning

- Makefile
- package.json
- src/features/outputs/qa/QAWizard.tsx
- src/features/plan/Plan.tsx
chore: update the plan progress message
> fix: enable retrying with a different answer when we fail on a question

- operator/Makefile
- operator/config/default/kustomization.yaml
- operator/config/manifests/bases/move2kube-operator.clusterserviceversion.yaml
Also fix the kustomize 'patches' which is obsolete
> ci: fix the yq bug in Github actions
